services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - ./volumes/database:/var/lib/postgresql
      - ./infra/initdb.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5